#!/bin/bash
# Run cbicqclive on a list of 4D BOLD fMRI datasets
# - Creates summary CSV file for all volumes in the working directory
# - submits individual QC runs to SGE
#
# USAGE   : cbicqclive <Summary CSV filename> <List of 4D Nifti fMRI volumes>"
# EXAMPLE : cbicqclive mystats.csv */*/*_rsbold.nii.gz"
#
# AUTHOR : Mike Tyszka, Ph.D.
# PLACE  : Caltech
# DATES  : 2014-02-12 JMT From scratch
#          2016-02-12 JMT Add HTML and PDF report generation
#          2016-07-13 JMT Add multifile batching and complete HTML reporting
#
# Copyright 2014-2017 California Institute of Technology
# All rights reserved.


if [ $# -lt 1 ]; then
    echo "USAGE   : cbicqclive_batch <BIDS Directory Root>"
    echo "EXAMPLE : cbicqclive_batch fmri_study"
    exit
fi

# Parse arguments
bids_root_dir=$1

# Convert to absolute path
bids_root_dir="$(cd "$(dirname "$bids_root_dir")"; pwd)"

# QC root directory
qc_root_dir=${bids_root_dir}/derivatives/cbicqc

echo "QC root directory : ${qc_root_dir}"

if [ ! -d ${bids_root_dir} ];then
    echo "${bids_root_dir} does not exist - exiting"
    exit
fi

# Default SGE queue
queue=all.q

# Remake a log directory
log_dir=${bids_root_dir}/logs
rm -rf log_dir
mkdir -p ${log_dir}

# Array and summary script names
script_dir=${bids_root_dir}/scripts
if [ ! -d ${script_dir} ];then
    mkdir -p ${script_dir}
fi
array_sh=${script_dir}/cbicqclive_array.sh
summary_sh=${script_dir}/cbicqclive_summary.sh

# Init array script
rm -rf $array_sh

# Loop over all functional EPI images within BIDS source directory
for epi_file in ${bids_root_dir}/bids/sub*/ses*/func/*.nii.gz
do

	# Check that EPI file exists
	if [ ! -s ${epi_file} ]; then
		echo "${epi_file} does not exist - skipping"
		exit
	fi

	# Echo command into batch script
	echo "${HOME}/GitHub/CBICQClive/cbicqclive ${epi_file} ${qc_root_dir}" >> $array_sh

done # File list loop

# Submit job array to SGE through FSL's qsub wrapper
jid=`fsl_sub -q ${queue} -l ${log_dir} -t $array_sh`

# Construct a script to collect all the QC results into a summary CSV
summary_csv=${qc_root_dir}/cbicqc_summary.csv
cat > $summary_sh << EOL
#!/bin/bash
echo -n "Filename, TR_secs, N_vols, tSFNR_brain, " > $summary_csv
echo -n "Brain_tMean, Brain_Thresh, Brain_PercOut, " >> $summary_csv
echo -n "Ghost_tMean, Ghost_Thresh, Ghost_PercOut, " >> $summary_csv
echo -n "Air_tMean, Air_Thresh, Air_PercOut, " >> $summary_csv
echo -n "DVARS_tMean, DVARS_Thresh, DVARS_PercOut, " >> $summary_csv
echo -n "FFDisp_um_tMean, FFDisp_um_Thresh, FFDisp_um_PercOut, " >> $summary_csv
echo "FFRot_mdeg_tMean, FFRot_mdeg_Thresh, FFRot_mdeg_PercOut" >> $summary_csv
for qc_dir in ${qc_root_dir}/*.qclive
do
    cat ${qc_dir}/qc_info.csv >> $summary_csv
done
EOL

# Make summary script executable
chmod +x ${summary_sh}

# Submit summary job to SGE via FSL's qsub wrapper
fsl_sub -q ${queue} -j ${jid} -l ${log_dir} ${summary_sh}
