#!/bin/bash
# Run cbicqclive on a list of 4D BOLD fMRI datasets
# - Creates summary CSV file for all volumes in the working directory
# - submits individual QC runs to SGE
#
# USAGE   : cbicqclive <Summary CSV filename> <List of 4D Nifti fMRI volumes>"
# EXAMPLE : cbicqclive mystats.csv */*/*_rsbold.nii.gz"
#
# AUTHOR : Mike Tyszka, Ph.D.
# PLACE  : Caltech
# DATES  : 2014-02-12 JMT From scratch
#          2016-02-12 JMT Add HTML and PDF report generation
#          2016-07-13 JMT Add multifile batching and complete HTML reporting
#
# Copyright 2014-2017 California Institute of Technology
# All rights reserved.

if [ $# -lt 2 ]; then
    echo "USAGE   : cbicqclive_batch <BIDS Directory Root>"
    echo "EXAMPLE : cbicqclive_batch my_fmri_study"
    exit
fi

# Grab output filename from arg list
out_prefix=$1; shift
out_fname=${out_prefix}.csv

# Write column headers to stats summary file
echo -n "Filename, TR_secs, N_vols, tSFNR_brain, " > $out_fname
echo -n "Brain_tMean, Brain_Thresh, Brain_PercOut, " >> $out_fname
echo -n "Ghost_tMean, Ghost_Thresh, Ghost_PercOut, " >> $out_fname
echo -n "Air_tMean, Air_Thresh, Air_PercOut, " >> $out_fname
echo -n "DVARS_tMean, DVARS_Thresh, DVARS_PercOut, " >> $out_fname
echo -n "FFDisp_um_tMean, FFDisp_um_Thresh, FFDisp_um_PercOut, " >> $out_fname
echo "FFRot_mdeg_tMean, FFRot_mdeg_Thresh, FFRot_mdeg_PercOut" >> $out_fname

# Loop over remaining file list
for epi_file in $*
do

	# Check that EPI file exists
	if [ ! -s ${epi_file} ]; then
		echo "${epi_file} does not exist - skipping"
		exit
	fi

	# TR required for high pass filtering
	TR_secs=`fslinfo ${epi_file} | awk '{ if ( $1 == "pixdim4") print $2}'`

	# Number of volumes in timeseries
	N_vols=`fslinfo ${epi_file} | awk '{ if ($1 == "dim4") print $2 }'`

	# Splash
	echo ""
	echo "------------------------------------------"
	echo "QALive : in vivo quality assurance metrics"
	echo "------------------------------------------"
	echo "4D EPI Data : ${epi_file}"
	echo "TR (s)      : ${TR_secs}"
	echo "Num Vols    : ${N_vols}"
	echo ""

	# Strip .nii.gz extension from EPI file
	epi_stub=${epi_file%%.nii.gz}

	# Create a QCLive directory at the same level
	# Leave deletion of files to user since this script reuses previous results where possible
	qc_dir=${epi_stub}.qalive
	if [ ! -d ${qc_dir} ]; then
		echo "Creating QCLive directory"
		mkdir -p ${qc_dir}
	fi

	# Key filenames
	qc_info=${qc_dir}/qc_info.txt
	qc_mcf=${qc_dir}/qc_mcf
	qc_filt=${qc_dir}/qc_filt
	qc_tmean=${qc_dir}/qc_tmean
	qc_tsd=${qc_dir}/qc_tsd
	qc_tsfnr=${qc_dir}/qc_tsfnr
	qc_mask=${qc_dir}/qc_mask
	qc_brain_mask=${qc_dir}/qc_brain_mask
	qc_tsnr_mean=${qc_dir}/qc_tsnr_mean.txt
	qc_mcf_par=${qc_dir}/qc_mcf.par
	qc_mcf_mean=${qc_dir}/qc_mcf_mean.txt
	qc_dvars_ts=${qc_dir}/qc_dvars_ts.txt
	qc_roi_ts=${qc_dir}/qc_roi_ts.txt
	qc_stats=${qc_dir}/qc_stats.csv

	# Check whether MOCO has already been performed
	if [ -s ${qc_mcf}.nii.gz ] && [ -s ${qc_mcf_par} ]; then
		echo "Motion correction has already been done - skipping"
	else
		echo "Motion correcting"
		# Run mcflirt on QC Nifti file
		# Output file defaults to qc_mcf.nii.gz, parameters in qc_mcf.par
		mcflirt -in ${epi_file} -out ${qc_mcf} -refvol 0 -plots
	fi

	#
	# Non-linear high pass filtering to remove slow baselines
	# Standard step in FEAT pipeline

    if [ -s ${qc_filt}.nii.gz ]; then
        echo "Temporal high pass filtering has already been done - skipping"
    else
        sigma_seconds=50.0
        sigma_vols=`echo $TR_secs | awk -v s=${sigma_seconds} '{ print s / $1 }'`
        echo "Temporal high pass filtering : sigma = ${sigma_seconds} seconds, ${sigma_vols} volumes"
        fslmaths ${qc_mcf} -bptf ${sigma_vols} -1 ${qc_filt}
    fi

	#
	# Temporal summary images
	#

	if [ -s ${qc_tmean}.nii.gz ]
	then
		echo "  Mean image exists - skipping"
	else
		echo "  Calculating tMean image from motion corrected data"
		fslmaths ${qc_mcf} -Tmean ${qc_tmean}
	fi

	# Temporal SD of registered images
	if [ -s ${qc_tsd}.nii.gz ]
	then
		echo "  SD image exists - skipping"
	else
		echo "  Calculating temporal fluctuation noise SD"
		fslmaths ${qc_mcf} -Tstd ${qc_tsd}
	fi

	# Voxel-wise tSFNR image
	if [ -s ${qc_tsfnr}.nii.gz ]
	then
		echo "  tSFNR image exists - skipping"
	else
		echo "  Estimating tSFNR image (tMean / tSD)"
		fslmaths ${qc_tmean} -div ${qc_tsd} ${qc_tsfnr}
	fi

	#
	# Regional mask creation from temporal mean image
	#

	if [ -s ${qc_mask}.nii.gz ]
	then
		echo "  Mask image exists - skipping"
	else

		# Temporary Nifti files
		tmp_signal=${qc_dir}/tmp_signal
		tmp_signal_dil=${qc_dir}/tmp_signal_dil
		tmp_brain=${qc_dir}/tmp_brain
		tmp_brain_mask=${tmp_brain}_mask
		tmp_nyquist=${qc_dir}/tmp_nyquist
		tmp_upper=${qc_dir}/tmp_upper
		tmp_lower=${qc_dir}/tmp_lower
		tmp_air=${qc_dir}/tmp_air

		# Signal threshold for basic segmentation
		# 10% of the 99th percentile of intensity
		signal_threshold=`fslstats $qc_tmean -p 99 | awk '{ print $1 * 0.1 }'`

		# Signal mask
		echo "  Creating signal mask (threshold = ${signal_threshold})"
		fslmaths ${qc_tmean} -thr ${signal_threshold} -bin ${tmp_signal}

		# Brain mask (use FSL BET)
		echo "  Creating brain mask"
		bet ${qc_tmean} ${tmp_brain} -m -R

		# Erode signal mask once, then dilate twice
		echo "  Open and dilate signal mask (5 mm radius kernel)"
		fslmaths ${tmp_signal} -kernel sphere 5.0 -ero -dilF -dilF ${tmp_signal_dil}

		echo "  Creating Nyquist mask"
		# Determine y dimension (PE dim in EPI)
		half_ny=`fslinfo ${qc_tmean} | awk '{ if ($1 == "dim2") print $2/2 }'`

		# Extract upper and lower halves of dilated volume mask in Y dimension (PE)
		fslroi ${tmp_signal_dil} ${tmp_lower} 0 -1 0 ${half_ny} 0 -1 0 -1
		fslroi ${tmp_signal_dil} ${tmp_upper} 0 -1 ${half_ny} -1 0 -1 0 -1

		# Create shifted (Nyqusit) mask from swapped upper and lower masks
		fslmerge -y ${tmp_nyquist} ${tmp_upper} ${tmp_lower}

		# Correct y offset in sform matrix
		sform=`fslorient -getsform ${tmp_signal}`
		fslorient -setsform ${sform} ${tmp_nyquist}

		# XOR Nyquist and dilated signal masks
		fslmaths ${tmp_nyquist} -mul ${tmp_signal_dil} -mul -1.0 -add ${tmp_nyquist} ${tmp_nyquist}

		echo "  Creating air mask"
		# Create air mask by subtracting Nyquist mask from NOT dilated signal mask
		fslmaths ${tmp_signal_dil} -binv -sub ${tmp_nyquist} ${tmp_air}

		# Finally merge all three masks into an indexed file
		# Phantom = 1
		# Nyquist = 2
		# Air     = 3
		fslmaths ${tmp_nyquist} -mul 2 ${tmp_nyquist}
		fslmaths ${tmp_air} -mul 3 ${tmp_air}
		fslmaths ${tmp_brain_mask} -add ${tmp_nyquist} -add ${tmp_air} ${qc_mask}

		# Save brain mask
		imcp ${tmp_brain_mask} ${qc_brain_mask}

		# Clean up temporary images
		echo "  Cleaning up temporary images"
		rm -rf ${qc_dir}/tmp*.*

	fi

	# Create orthogonal slice views temporal summary images and masks
	scale_factor=2.5
	slicer ${qc_tmean} -s ${scale_factor} -a ${qc_dir}/qc_tmean_ortho.png
	slicer ${qc_tsd} -s ${scale_factor} -a ${qc_dir}/qc_tsd_ortho.png
	slicer ${qc_tsfnr} -s ${scale_factor} -a ${qc_dir}/qc_tsfnr_ortho.png
	slicer ${qc_mask} -s ${scale_factor} -a ${qc_dir}/qc_mask_ortho.png

	# Mean SFNR within brain mask
	tSFNR_brain=`fslstats ${qc_tsfnr} -k ${qc_brain_mask} -m`
	echo $tSFNR_brain > ${qc_dir}/qc_tsfnr_brain.txt

	# DVARS timecourse
	if [ -s ${qc_dvars_ts} ]; then
		echo "  DVARS timecourse exists - skipping"
	else
		echo "  Calculating DVARS timecourse within brain mask for motion corrected data"
		fsl_motion_outliers -i ${qc_mcf} -m ${qc_brain_mask} -o /dev/null -s ${qc_dvars_ts} --dvars --nomoco
	fi

	# Extract time-series stats within each ROI
	if [ -s ${qc_roi_ts} ]; then
		echo "  Signal timecourses exist - skipping"
	else
		echo "  Extracting mean signal timecourses for each region"
		# Timecourse of mean signal within each mask label
		fslmeants -i ${qc_mcf} -o ${qc_roi_ts} --label=${qc_mask}
	fi

    # Write dataset info to QC directory
    echo "  Saving dataset information"
    echo "TR_secs, ${TR_secs}" > ${qc_info}
    echo "N_vols, ${N_vols}" >> ${qc_info}

	# Generate summary statistics and plots in QC directory
	cbicqclive_stats.py -i ${qc_dir}

	# Generate HTML report page (index.html) in QC directory
	cbicqclive_report.py -i ${qc_dir}

	# Add line for this EPI data to stats summary file
	echo "  Adding stats to summary file"

	# Construct absolute path to EPI file
	epi_file_abs="$(cd "$(dirname "$epi_file")"; pwd)/$(basename "$epi_file")"

	# Construct summary stats row
	# Use percentage of outliers (column 5), not simple outlier count (column 4)
	pre_str="$epi_file_abs, $TR_secs, $N_vols, $tSFNR_brain"
	stats_str=`awk '{ printf ", %g, %g, %g", $2, $3, $5 }' $qc_stats`

	echo "${pre_str}${stats_str}" >> $out_fname

done # File list loop

# Done
echo "Finished at : `date`"
