#!/bin/bash
# Run cbicqclive on a list of 4D BOLD fMRI datasets
# - Creates summary CSV file for all volumes in the working directory
# - submits individual QC runs to SGE
#
# USAGE   : cbicqclive <Summary CSV filename> <List of 4D Nifti fMRI volumes>"
# EXAMPLE : cbicqclive mystats.csv */*/*_rsbold.nii.gz"
#
# AUTHOR : Mike Tyszka, Ph.D.
# PLACE  : Caltech
# DATES  : 2014-02-12 JMT From scratch
#          2016-02-12 JMT Add HTML and PDF report generation
#          2016-07-13 JMT Add multifile batching and complete HTML reporting
#
# Copyright 2014-2017 California Institute of Technology
# All rights reserved.

if [ $# -lt 1 ]; then
    echo "USAGE   : cbicqclive_batch <BIDS Directory Root>"
    echo "EXAMPLE : cbicqclive_batch fmri_study"
    exit
fi

# Parse arguments
bids_root=$1

# Convert to absolute path
bids_root="$(cd "$(dirname "$bids_root")"; pwd)"

# QC root directory
qc_root_dir=${bids_root}/derivatives/cbicqc

echo "BIDS root directory : ${bids_root}"

if [ ! -d ${bids_root} ];then
    echo "${bids_root} does not exist - exiting"
    exit
fi

# Create temporary scripts
tmp_tmp=`basename $0`
tmp_array_sh=`mktemp -t ${tmp_tmp}`_array.sh || exit 1
tmp_summary_sh=`mktemp -t ${tmp_tmp}`_summary.sh || exit 1

echo "Temp array script   : ${tmp_array_sh}"
echo "Temp summary script : ${tmp_summary_sh}"

# Setup array script
echo "#!/bin/bash" > $tmp_array_sh

# Loop over all functional EPI images within BIDS source directory
for epi_file in ${bids_root}/bids/sub*/ses*/func/*.nii.gz
do

	# Check that EPI file exists
	if [ ! -s ${epi_file} ]; then
		echo "${epi_file} does not exist - skipping"
		exit
	fi

	# Echo command into batch script
	echo "${HOME}/GitHub/CBICQClive/cbicqclive ${epi_file} ${qc_root_dir}" >> $tmp_array_sh

done # File list loop

# Create a log directory
log_dir=${bids_root}/logs
if [ ! -d ${log_dir} ];then
    mkdir -p ${log_dir}
fi

# Submit job array to SGE through FSL's qsub wrapper
jid=`fsl_sub -l ${log_dir} -t $tmp_array_sh`

# Construct a script to collect all the QC results into a summary CSV
summary_csv=${qc_root_dir}/cbicqc_summary.csv
cat > $tmp_summary_sh << EOL
#!/bin/bash
echo -n "Filename, TR_secs, N_vols, tSFNR_brain, " > $summary_csv
echo -n "Brain_tMean, Brain_Thresh, Brain_PercOut, " >> $summary_csv
echo -n "Ghost_tMean, Ghost_Thresh, Ghost_PercOut, " >> $summary_csv
echo -n "Air_tMean, Air_Thresh, Air_PercOut, " >> $summary_csv
echo -n "DVARS_tMean, DVARS_Thresh, DVARS_PercOut, " >> $summary_csv
echo -n "FFDisp_um_tMean, FFDisp_um_Thresh, FFDisp_um_PercOut, " >> $summary_csv
echo "FFRot_mdeg_tMean, FFRot_mdeg_Thresh, FFRot_mdeg_PercOut" >> $summary_csv
for qc_dir in ${qc_root_dir}/*.qclive
do
    cat ${qc_dir}/qc_info.csv >> $summary_csv
done
EOL

# Make summary script executable
chmod +x ${tmp_summary_sh}

# Submit summary job to SGE via FSL's qsub wrapper
fsl_sub -j ${jid} -l ${log_dir} ${tmp_summary_sh}